---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:
  - name: Generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  #- name: Audit
  #  image: node:12
  #  commands:
  #    - npm audit --package-lock-only --audit-level=moderate --production

  - name: Install
    image: node:12
    commands:
      - npm ci
    environment:
      # Cannot be true because of node-sass
      NPM_CONFIG_IGNORE_SCRIPTS: false

  - name: test
    image: node:12
    commands:
      - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: Build
    image: node:12
    commands:
      - npm run build

  - name: Static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: Docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-muuntaja
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:
  - name: Publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: b5224Ecat/2XR9619lVRjD5kkg3hbguE/Yif4BenqP9ZmZ02Gefu6bbXGzaMT235tQ4=
---
kind: secret
name: docker_password
data: WJqVzBHLzcenRgfyTvUTUITncrlnumurB2Dea0FNyLxLxr01DwyRQw19LTyxyK0sX7gX4/cjfmXPKDF5O3RCJ/cEENe9MFGoNmbvgJ2FhQqtChXooViTHNj5EH4=
---
kind: secret
name: ssh_key
data: iK5ckooflLyMeiYg3WF7iQ3r123DgR8nAlMyw/bk2jZMPKBy/yXTUjwNTSKa3z9DtChCJUO4gx45g5drkusnHuu9XwQeM32PnQyZ78arDrXj3fGOgT2/JeNpnigNWbfr3ttg7nt4X4aO/WcJhxsEWo3gz1XZfS1nuN31BPWC+kiK6cdYPenPJg2yXu1LFkPct6BY7iU8Wuh1AaITzFd21oWu4DFj9HUlRRKDipGPUFa5m/gG1DqQmD9gugxE4DZX+lqs8Hm9oHOShE4G4MYq4abskqrVhtvrTjj6GaOkS9ia4Cq65gISoxhhjQJGkA9sW/Ldp8s09slhpCPkggm46sFnztqzz+wlT9OfIloFKBQx2dOvtEyavPo1XbJECVlBmf3ZOHQb4VYkrKcAjRqe66RnP0uVnrn52TRPdaylkQk9TUgkfg2VcYEaSLEtqzWmkMc+IW+dAjrD9nkiMr9R6SFOEAKMPDuKaNnEe28q6Frdt03aNhPWZi+cW5BFMg/HUgjwtvJIdgfsKeAiQFDAz8zznb+hnylpQdfph6t0wHjr1hnVqbXjlJs+P8VHnKv3pqKcNckF0bAOXeHg1BqwLxGW4GPKad66yeu6bmL0toYqL2Vm8wQae2GKNwBpKQV9C3rHMS1WQCMqrRYyaqpSamDd+98onajphTter5Z2LpXegHDkKSK43i4BBerfQ36JVKU5vLPYh2IMHwe3zl+bjekWf0puZDYYI1/RWRtJRUCYN6WO7iujC2py2BfwDGL63SW+Cc6NIMOrxcTYrlwaOl5T0jVecz5pAuzpT0sSmFTJkF5f0WzKXMntMfy9Iur+Zl6hLNnFjSOUF04Dy0vPSNeOoVyJdo+vTPAJUOnkpErgRmdpuFess0NkpzzexeSlViG/HG9e87NpPl1/jZ0yyZN9Oanw/joqSFZJXpF1vDayKBeN18tTbmVALy1Y1KeV1m4AZ54Ma1BWUFjDNlzxO9owsxtNx6/Gz5zD4c5CDiIyeVkdiFpOiASjL1hNRLxD62k0oJRn17oKg4RUL4p7M5uLZK9aABnYnNUHOoUqHCHxq+GMZsgxpDOhrqKdLopDHYNxC2WkF3jNFYU2ZvyOgAMw2vRh1fatLygUUWxeSDckE7jRBeOpxFGgCn8lW0FkWbJGPvMGch044wxLE21oJiQNxhXBoW0qETs7pXbJCyyEmioec6RrBCi460KDLxQzLDfjGCWB0TYxguccVbpKkFD3g8/jm/emuSkWTJguP4+kc9zLaDSzk8GICcuvLkU1V8xcPCCTrTf5/bMAdALnNx2dZHq6fVlfSFGeUScp82Hz55XEPeIhvGn65KCI0Co7UgMlW+/WLmVU7g+drNeOnzqFmBf8B5fUB3i6LvXEGg9aoWZsAhPmadBIAT9+VEPgI6eHy7rDRPHgC6sZqPc7lNYNOTxxsgHROXrhcIS00Sbi4+MUUr3zcgRq7hNC7FoWeplBX2mTYXW6F6jugqqDlHGSo17+R5DT9yRYKN+wU0hvpJzJT85N8ZnjByFFnL0Pk0y4QvlrhMrg0IdLEjqc93NBsZmzsyGhhtigzhSAVYTMFKcGn/eP0TedirEArfrFagLwvH8DOe6kci8s01VlunkV+2c4G6GAzoeSnlECqehpuQiZzcSGfIFlcpnDMktl977mvGdkNnIiHCIkqcwnvOKuCLTgR22A6MvDUp7yxM4Vwn4dB560feYwP3C3+NcQkPF0MUEwNFRjbdFtC2WPdB8gOtI13+/Mu/tpjgmiKlMWUpt/eAiIQGowrBEszBvpScGh3UJR9flx6YqsRjVt8BNrtakUKUp5HJ2tj8SUrcld7ZHix/xhwF4TtrdE+kIfVjrgKTFX7yLYnP2+hny9GpFo+golDRdS2oiuyQ+p9rcxP9DRM/tqkVSrYiMV4OK+WiWaTxsiGLFUKz+ypVY34AopcLnH8mz+KHsgjYP4pneeQiJxQGItcbnYJyrsBw5+Zb2IPenkvS3eTdU1mQmYhhAejaZ/MyF8ep3lUzEytIiXg/oMoZlrrUwWu7iyK4H7DCv4H3Rysc+iqePhJNUyJyHArlSnba6Iqiv8qsM8m6FvMJqSpXbvyKPv2QPdNzOOYqKT3/dv3bPtu2KRhAxxhknvrvZvlxehEGN/nZ9vQtB6aUa0PjzRPUgq/R8b4K35bjBANzd8hMh+ANcdS2VGfFKXYGFIWS1tr4HoRxQdLrQheSODlDjaDZbXAo3wnPxoa5xRDXmVc/Hudky482bvcGyQ1U279BQdMM2VWZiWth7s2ImIYCJgUQTvhOr8IJTSI8q3h/FJrVSy7FplYQS87obip+rijtJBHYa8tqMnzQImUz6xs7JmU2EomE9PCF2g60hCZ+jWJIPefgCsvxyjVce2hXBuAJhsdFQPmB435WlF5KbESerlW9XssJNalCyA7Z4V/jb+q7D21KYO+ykuX4X4SyiyHA+QzUr7ntqeQl5Fh5gwnmDOtfN0aA6pJdPXsOl9Oev8OwrYq7wTGZiJZvQqLldUegY/zy6beGblLWuK3bqSEazC+ZJ8DhYzHtFkOid+h/1bxCZhMlAZby1rYtXGXlxtx8gegzGFD4PkhRvZMcbf4fSl3P7GpZdtvguOZWMlSFT5Poy2gaOjXpDA3qiUbmqJyMNgPxMr7cgeH6ekrFLuReHS+GD3Aklxn/VaUny9elxgvCKejJVMEvoh0F94CPXlNfYIxK6fIL+Kmz2dtymtZ/qkRrET0nTENND3Y2SYZzY2sYnZdMopXiPI6FdDAIVWN/mpvffNFA5gXxz7Zbpq+G7dKb/W0rVNxMt8hbDVx9m8sHT9tCeAzDY6PmvvzZeczhgawS+gSVd8l2cHglxOXUZwMpE3ie46qAyJ3jv2zG3XPk6oyWY9H2gFjB6GNcSM86ejlblL1uga4QZf8yHPOkTY3I4fYLMOYTKpeWgISct0UWB5UJK5F1qYkZxTCRAUfj1SQJWQRRo/+cSB280SoLhNYxwUAQnyP0AtM7lMvgkySxHnU8Lz
---
kind: secret
name: gpg_key
data: B2M8rm8+RSlZnLhg3c8RhTaw8pN7JkyJeeDoVQwSCRSbNKT+YsWrepkvcPyIpnC94hzZ2i+9lp0nUEULPuB6T9yrQ3rdadBbnkybRa1c1Td9nHnDdY/Fyd6K4XC7+Mwh2IyFs6ES8MKIuiU5etylOdVRkUrclvrWejtIoFXlVJqu74XiNYworc9aj0Ox4srsB0R8oaoYMdVg8c4KNeWegvbrPC0+GVezN+3HN9/l4H98JZscZIyjybfj5xX+tidGsnqPbd4y5JdoEIu8JpY0WNr0ccr+D0Jg8lxkWyBGBOXzXK7q2tCZghED9+PK5zf7udthV3cZq5ZR6/quNJzI9mQJZiYe7n5zSX3Kh+iVJ0RtEYgNOrHLlgEe2AxS1z2p6sDvc2jHFKSBW9M5RRXd4YMCNJJFUeRYErqOWdsvlJeDvHlRK8C2Wv30aOwe7FxBoWotUENThLHM8SErpvHOuN6UlIzP8lzKq4NITCE7ffdxCHqQhuibVuMph9jjTN0bOGzENh5m8hvH0Q5WFD9rnGuqByE/Vjl1fR3M5TrdaZkziSPhYm9jad7yB/jUnmeEKs1O3FD1/NcIRy1YKnmIs77z3JqTpc1et3uvBf78HWnZu0CVzVuHoOD0yuFuH9LOijz7F0u0WCJKC2K29FlX/rVimk6aYjueSktu0CFz/VYBqHGyVX6vXuk0BZ4CwPdPDiQxYtnl+5WKD/VnfB0H+9wB7AQR6mFDnGvm4sipJi8ATUF6/a0tCVulY/eeBTPebjsV2xBQdHUbBa98UBUJffeleYktsAD4DTtay6K4MLvU4DqVo6EOrJ6WwQHYXDdKS/tlyibE27YVAc74ymO+jtEusg4Iy2MvkgYKZYua05P8UJauj+Az1f7XixR6xQu9jmSmbSxeX0IX7lI99gEY9JrUbBcPtvlsSRpsVpsBlo+h4lArq/RgvgToM+FiNgsRqoNtLEnhbbryTy17usrm36KEgfXEuhE9TrzKfdzMqrMQdK4foAoC8WPiBsfdzn1hD7wTR1FVdGLbRpEnFCO3vM6nmbEDXGubKHIdbA3Yp5xjiCKMj02HlS7kcHs0EcL7z/p61vEPpI4IbTZCGpU/D/TOhC4hFelZiXQfqFWWwtz8Em98b2ySKgKQM9N6lDk3AsXyK2hUFdGrfSPQKuuoxAlvCpun6S8tprnRHPwivsv8Kdj40SxVKLMt4k9j5EIEZB6uv0Gz+1odXfucNCTTHUp4jRa8GFiupcm4XH7JvrvO7g2GIw6hNhGYlpMokzd57VKtGpr1LvspMhK0xdUNHUF7F3kRtRS8w07KS6I7pm/h/vjd4hfSUxTEB2JjQoxYXr3XKX5Kz6vpmCgz4xy1sArQe3xTRLuE1z7UUGmlcKjTAGtnb7j4I1YlFzUeHakMjVPy5f9aKRRnMQdO5n1KhSfR4PXmQ5B1Csju1igF3bP5cGW4+ANBpdgQpeLkA/SLw6nNJEKU0lq2MdnMWvWZIiZlPxb5Z1VrYtZHa8PQu2x0DTbEJu/BQiSXNMLn7qmUbpds1BHZbiVcS56NyskyoS+elfryukbQ679xbMFj2LglSSBvmu11OLEZnbxKGE6Ua9Z/XmDW6XWiawcpccFRbnZxvtNhzbSACEAmoGCZbQrJAG0POCRp03ZJjbfuvciFP7KsGi/i6rUjHpwjlHXSN28WUaXBm3Oa/MadSLenPYcOtSnOq13Ox7TzC7ftIGAKXIBqNhDFwnSsZOfIzjKaa8FSKT4usLilO48X4Udy06TRHcSm4utPUeAUm2/RV24t9pJEi6Za53IJ7TlVV4FsXmtvW+f/fgyPNZ0p9RaGdvCWaOWbZhxfS2fdNmQunljrM3Z6RvH5BrCyK4cOGbnZ/puZJLQ1GRZE5jMqbBEdSo8NtR58B526jz6iM5g+zoCYlUkn25Xy3ovgvTnIwYHVH9nAIn6C/qj4RfZADOaRouzyYp4efl86Kv0/FcEB4NsfHI95WonfELvmDIlxv0xnqHW3VVW8w6+/ZzffCw3Ecfp1793MOqk3yRfo+2JkQXPUi7vLKn1+y9gRg5+A4QcT7Qgwp4Fqk1shexEioaHpDELSV4vLgfuaMgu4RBzO3vaVP41wb1GTh9xJQ045lmqUmkRYYfVQQsi9ubZHtpLINMIjz6oFDRJLDjG1I9LmVTKqHbRl/As3nszSm1St5KYwAJ18wOm2wjSkdkR4qY2h4IQnOul+34KPC8gH6Bh7jhPd+iRsCb/cqfwlOqelT0A+hYS0qsxqOPHAZftbVCUcWS4bzMmPgkCQydoTipxU9MBSJcTXVIl/JEkiLsFZimPtP9ISf3y/SbpepQRR+NbGGpJ9QYyxuKP/MDiT3akFMCKm5LJerb+RcHCVlO0zQ5e43QQ9LRPc/MJ3qvCr7x1n0vPZo2UCtPEsyWJFYT/BqGs8d9MN/QcpLD3k5YtHQ+Yt1L32SZZJcPMNWX8el8HcvjOdnNJ9yyMB67vA+B80UuzUCexxuugjq5OMTAaNataKLgOFHGeqO5WpM3h+Yj4vrx1IJeLyNSlsSyzwC4CKmdb+M41C2iB9Im+mo7AFQ0/V/dmZK2tqvSHpu+q9ivwc2Yib4pvRI8W3QSilOYU2OO1c3l3RLEREoFHMIy0y1jtsnssIvjH2W3YWrGCvs84W+MDf4qf6evKbSzKCN5Zd7/xuiPxYjDoC9AbZMkGP+KsLJ+D9D0eRjKXX1WWYFbLiDQWWl6S/GzDDMidTJYWR5bvrg5rnElGEqCNaqSAMHZoeX36QML7G5WwOYUK/S3PDdVbhUfjKoWEMc5t9s9ByfWps+xLvuyBwLZh99f3CaqB5tRHoWLPJ982sBWiI7Z54Wa6TsqdF19CDBhjcd3RX0mwGxQPoLZortM1Sr2FHC1Jf9BKVST0o8Wm2NVcbkSD0OEzzRHnH5nmZ77RE3T0WrCjSiykX0m+tgKsgSrXxoAkZK4uN1afjiJSNMmka6hCLWL5sDrxm/iNiKumJt7GYnnQx9Y2GVRDI5ZGyKBF4DHmK41M6CeFib19e5xfYKiB8O+NPoTvsCg3Nievhja1aGID4TYbe4qDGu+ryqrJ3hOIKppeGsGfJloKVWyHWWa1JewKS9+Us/t4CMK2PGUmWiuUOZ1qoZ9XwDVSIIYEVvIhHxWPwGDdHyZPBRzmxX7w57BEl5l8B7Mhteke6f1Sgd6B71x40byP9IY46a029JOMHJztFfskO/hThdyayRtXU70qoDIA26rCRybLj/xk/xTfxTaoon+420IT3fFaafcUkZMDUhnThtaFUMPhjf2/nZQuh49+EjK/LfxOGsPrj3gKkOeB2Kp5Va2X+mawoAIywclhmHGbuETjeLpfZAeLxuVrhAN+xB0cY7c1XIbcM4Qqq/3rG1YPQb0X+uZezgqlqzaEpPvPdqPYDHG6xBg2zV60FouNZkjRZBu2obg89lbjEJD8flH8Z+pJwDyApK5eRRRATmTmJAHsA3HBnajeiIgCdW+RADhKFcSGwenwo4TlonEtIwxc4j474Nvx9j2+omaT3oUoi1e/24814HEqxRY37jD3Mh1DgH2/9T9c7Twm/4IDwa2Nq2cRN1zzT/9xUFEfze6VYmbkQGC6/T68l8/KeoEFFUes1ynyHqu0+FJlp+HsDnFGS/pLsddcQwnsveAHmKR3W1n4oZuUqwL9r3AH6BeZH5qCc6yl311H5GMdslioz4Wue4Hi6wbniOdKcwmu6LYPywKni78sxEASAjJwLKrSK8JdJyMa3BWHhJSxCCsTZCr9SONgL+GbXFLIoFUSpV8aEr08O2xYclHbU6noXAA2DDEDn8nUmmzN4t+khnEkCz2JIdr62Ouh3nFH10I5/LihKwkHD4JKSpyjkDlV602zxLftROJVWahyIqmi5DEq7pVRLTr/ZkNWXsTfo9oEcZg6PbRTiizOWMKpsvKvSRD0rBZ8DWIxbJ0rD+AideZd57Bx+I+1qMTmAAv8oT4qgiRMmrYSmI32ittoqvJ83WkG4vw5pN7JipP8TRbjU3mmDl+rDRtp423gVGJOOB4Q6VhPZulaiMI6VxG363FL/+YtAhJWx1veSZKsq2WR/+auHKp65fQq4yMN7Z+yS5qRg/DPKso0zjsC2jTcOp58jPtXcf0VEaRowNj0wQy9PXYYQWEH+4BUtHgDXpNT7UUK7QY2Myra+QsAtOk/zrXr6F7qxoPdiztiJNh5NdEWuOa13iOLmDJkGwmdMImtsic0KCeiSIk2P+DMfXzgBZjihpSZnKn6FkvqlNzUSA7JVLh+bzcZkc4XWHBnwlVdEkTDpBuKJ7s3pIMekjI8JO0EanJfCctUsy8FuMDNdIhmk6C3Uc0wqVyOG6teQkocMc7bu46r6Aro3er5xn/DOsRksrkZZlsv/IWucXp67MPW6w3SYY2q/yzPnYfsV9W+yr5muK8E0mOCRV3j1Bz2oB/ezqFJy++QDCBnxeh3+XRgGppX84flPbjtl+2OxmQOoG/950mTNlXkUADQQip3ro54yO0GAoSlUd4aHWnRphMPJxQJJzgKbMUa4Dqs6VDX93Ko+LmgSCDhuFvF1KhbWQxkZQVHTVHAW+QaXb/B1MGKWdUjhK9J2w4k+KNoNjbQixPB//6Fb3R1i6zeyLZvj0a6K4Tf25t/+VBZ0uCnsCrrviZe7Z3/41r1rYAcB0+fBEx3EXCHV3xFql2A25naDqP4jwG0+vHuF3bRhd5xvjGvsqXcJjNpE8UUjGIRxgJTZ13wTAiFX+ZlKTfzX9AGfrZXxLDowGDsFW4WuVGTxyIwcgk21UMDa6HHA3DeQItCoWbBUA2b3SESwnvr48o4AlJBu7SeFfP02sryyZptxW+SFeCIOaI1s0/38FYNcZQgWmXnoicyboF74Br3E94PHq5J35u8S6JEUg3ZFMq/A53Q5gjjIw8GZ5EsrDgGo3YD6Y/0rH9UaefrFQgIQF7IbjzTsWCXbfn7vJduGCDZqG5rMyz+2jGCFDLBwdbSIZQbQCJiCrQ9bywIDXOXdRxB5RqRWQ8y9/mT0TRAuBQ0qBVpTlOwAoTQIddxYMEIxjg5U1sneMo2atcVFIhxeVGa9peyN0dKpQFFTK998jPi5mPFgsiTAtE2bezh3dfT7LkD8seJWd4QS5RCDhi7pZ9fYf5dJB4VhGoZ8F7g1jQOWKW0lcX/XYkdETbN2MY+OwZrXrVMdw7ABDjrvOqfqswRJpndUJZpOYpkA5R+FQcNzcX7emWG5ELhiL2ohtUGa02OFiGXEomRoMFLGE1sAI2Csf5biI13J6VSxgQkzaUEnWo9qy9The9rMZuSjgK76i6cAPn2aOYWY01CqU/583Wj6yWcKjoH4wuL0mY1B6qJc9a6SJKvBwk9d8+0JexKfN8xOc3GH7E5YJ6rVuwh0V+fhkIS561vJZWJoqDKF3wq6nt9g4dCh8DN5ia+tyRI+XVgdgx75CLO+16VqVwsuS88ONm6XJxTECRSfCLHBtdyN+6IvIM2f5L9bUQVTTI62EEB6NaqNYCsduJBBX1v1/3Rlo/GLd5HCcvoMCPBawdAh4CmyUc8TxSoE4dnsydh4msvU1kQ6RIx2I6JGhPsgEC2HPLxOBjX8dtYYUZi+7eA9BQbqiP+UCwTJeecqHKq+f5XjyngJAb7Q1SQOzESJLpZj2KgP8mNcaa1a5dU/x497j8bw5w8JhBaZGoI9j7e2vpfSlY97hkwtn5M+a1n8VWjZ/wOBBoR8Dpm2CTolFyZcO6plx3/h4pSCFB+DkOfsuuE6daI/WOsLvib6uqFYfKm5kcDv9hgLYdfLA+dacCXYfDmWqOhGE/l4yX6c1WYyhIO8HnVkJZlcHSJtzlrnEbry/sdmRxDoPa0sEg85JL7ciZIqgUF/8As98YF2XMMeQN+NdJtMuKHtRp0mZFXvWrI+jcUdA3bgJ5uALzQJUjGdIVopd2khk+qffYZuNVVOSUj4FrTxeebp35N2cqWT9uGlRZ+ikToblw8m/MU9YFzt0C9jLObQMrPUbPTgC8TXdGbM8ghoE8vVhlREeZbR1ym8QA+4zlCneoGEAQlGCLYN2hnbqKiiuJ+9dT/0yLFhCb7gjSJRgR1/0AYRDAO6AEfb99f4qG4cm5TXIgPLaIMPawLoaL3RAF9itTm5++ASz/r+8zWmWOqFqqfMZbE7193bT6Pew9GAviNcJBMCmTqYBY12Yuqn2AfnOa0EDNsPdRQjDcGsoqkih3j5ZJmMMkNrtfTlJ3cgRuIgVPJJ9dkCCFzBKXpy5qHSJCRPUzRAI8QoO87pInG4ZH9YnRtzFyAABzPAnfpFl4yjUagTWqCJ7ccTlgPc/lHyUG8rFeiaDV5HX8QNqDbnGb/tgEYugrmbqQnolyk+ghc0AxR17mwwIi55eFXiVCsJsaYFsRD5Vz+sXEm7WuxgU5/y8pIAGMXDMfY6N00ylnmc3+eiinZy13JNfN53as7I6e/234Ya6WvSpIaZICXP4GUvVBU9k+9DvJ3EA6Vts5ttmnKHeygNJkxIO88vSSD/YEs9he1aT8IjoKhegRDKh2X/ELI/ryVdDVMV0UHNYv9byj+u7/8Vuw/JPqSvWFveYXmRnglRAOFHmBRUWP2M611jl1cKxQ5T3iPftmqEqp5TKfjiFdvQsVAVIbo7rtSynLIHXLHzvsRkD4MVcaoVadzHQ5DHT6nGzZWkdoXqMSIG1g==
---
kind: signature
hmac: 1e30d66109400c8d5c4004f001467d1fc9a185242843da0ac8843260eb1047a0

...
